vrrp_script chk_sagedral {
    script "/usr/local/bin/sagedral-ml health"
    interval 2
    timeout 1
    fall 2
    rise 2
}

vrrp_instance SAGEDRAL_VI {
    state BACKUP
    interface eth0
    virtual_router_id 51
    priority 100
    advert_int 1
    authentication {
        auth_type PASS
        auth_pass CHANGE_ME
    }
    virtual_ipaddress {
        192.168.1.1/24
    }
    track_script {
        chk_sagedral
    }
}
